### ISSUE TITLE
Compatibility with labelled 2.0.0

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#100]
La version 2.0.0 de `haven` est cours de dépôt sur CRAN et dans la foulée `labelled` va être mis à jour.

Cela entraine une rupture de compatibilité, la classe `labelled` étant renommée en `haven_labelled`.

Une fois la nouvelle version de `labelled` en ligne sur CRAN, je ferai une PR pour mettre à jour `data(fecondite)` et `data(fertility)` en conséquence.

**Comment by larmarange** [comment]
Note : il faudra également mettre à jour `describe.labelled()` et `lookfor()`.

**Comment by juba** [comment]
Ça marche ! Merci pour ta vigilance, et je valide la PR dès que tu l'auras proposée.

**Comment by larmarange** [comment]
labelled 2.0.0 is now on CRAN, I will prepare the PR

**Comment by larmarange** [comment]
PR prête. J'ai déjà augmenté le numéro de version, mis à jour NEWS, et appliqué `devtools::document()` et `pkgdown::build_site()`

Cdlt

**Comment by juba** [comment]
Merged, merci beaucoup !

**Comment by larmarange** [comment]
Merci !

Prévois-tu un dépôt CRAN dans la foulée ?

**Comment by juba** [comment]
Oui ! J'essaie de faire ça dans la semaine.

**Comment by larmarange** [comment]
Thanks

Le dim. 25 nov. 2018 à 14:50, Julien Barnier <notifications@github.com> a
écrit :

**Comment by juba** [comment]
questionr 0.7 est maintenant sur le CRAN.

**Comment by larmarange** [comment]
Merci

Le mar. 27 nov. 2018 à 09:53, Julien Barnier <notifications@github.com> a
écrit :
