### ISSUE TITLE
Moving lookfor in labelled package

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#103]
Hi @juba 

Following discussion raised by @briatte in https://github.com/larmarange/labelled/issues/44 , it could be relevant for function `lookfor()` to be also available directly in `labelled` package, in addition to `questionr`.

To avoid code duplication and considering that `questionr` already imports functions from `labelled`, could I propose the following:

1. Copy the code of `lookfor` in `labelled` package
2. Release on CRAN a new stable release of `labelled`
3. Once done, update `questionr` to import `lookfor` directly from `labelled`

What do think?

Best regards

**Comment by juba** [comment]
Hi,

Thanks for asking ! I completely agree with this. `questionr` is a bit of a mess right now, with many different functions and a lack of global documentation. So moving functions to a more specific package seems a good idea to me.

**Comment by larmarange** [comment]
Alright. I will introduce `lookfor` in `labelled` and once a new version of `labelled` on CRAN, I will submit a PR to questionr.

**Comment by briatte** [comment]
Works for me too!

@larmarange, I think you'll also want to export `var_labels` to provide the user with the simplest possible output, possibly just a (named) vector of those labels:

```r
#' @param x A data frame with some labelled variables
#' @importFrom dplyr if_else
var_labels <- function(x) {
  vapply(x, function(x) {
    x <- var_label(x)
    # handle missing variable labels
    dplyr::if_else(is.null(x), NA_character_, x)
  }, character(1))
}
#' @example
if (require(questionr)) {
  data(fertility, package = "questionr")
  women$unlabelled_test_variable <- 1L
  var_labels(women)
}
```

- The function is just a `vapply` of `var_label` that handles `NULL` labels
- I'm importing from `dplyr` because `labelled` does so already

**Comment by larmarange** [comment]
`var_label()` could already be applied to a data.frame and return a list of all labels. 

An `unlist` option has been added to `var_label()` for returning a named vector instead of a list (cf. https://github.com/larmarange/labelled/commit/1286c67e638258f3722b649cca7e05b5ae7f2024 )

**Comment by briatte** [comment]
Nice! But don't you want to turn `unlist` to `TRUE` by default, for the standard user who does not know whether his 100+ variables are all labelled?

**Comment by larmarange** [comment]
I have two reasons for keeping `unlist = FALSE` as default:

1. for retro compatibility, a new option should not change the default behaviour
2. by default, `var_label()` should return data in the same way it is expected for `var_label()<-`

In addition, the best way for a user to know how the variables are labelled is to use directly `lookfor()`.

**Comment by briatte** [comment]
Understood.

In that case, I will suggest (for the last time, promise!) to have `var_labels` function that just does `var_label(unlist=T)`.

Motive: you want the user to be able to write

```r
var_labels(x)[ grepl("Something", var_labels(x) ]
```

which is intuitive, because it looks like `names(x)[ grepl("Something", names(x))`, and short.

**Comment by larmarange** [comment]
By the way, the default behaviour is also easier to read when displayed in the console.

**Comment by larmarange** [comment]
If we add a `var_labels()` method, we should also introduce a `var_labels()<-` method to be consistent with the other similar functions in `labelled`.

Also, it will be only used on data.frames, while `var_label()`, `val_label()` and `val_labels()` are intented to be used on both vectors and data.frames. It is important to remember that by nature labels are applied to a vector, not to a data.frame.

From my point of view, it's creating more confusion and complexity that it solves issues.

I'm not sure that a syntax as `var_labels(x)[ grepl("Something", var_labels(x)) ]` will be used by a lot of not advanced users. If the need is to search into variable labels, there is `lookfor()`.

**Comment by larmarange** [comment]
In addition, what should be the equivalent for value labels and for user-defined NAs (`na_range()` and `na_values()`)?

**Comment by briatte** [comment]
I surrender to your explanations -- it makes sense, indeed, to match `val_label` and the others.

Suggestion -- shouldn't lookfor be called `codebook` or something like that, if it can be used to produce, well, a complete codebook of the dataset? I also like the [suggestion](https://github.com/tidyverse/haven/issues/237) to use `look_for` (`lookfor` is the Stata name`, and there's [a package](https://github.com/leeper/lookfor) named that way now).

**Comment by larmarange** [comment]
@briatte I have no problem to rename that function to `look_for()` in `labelled`. But regarding `questionr` retro compatibility, should it be kept `lookfor` in that package?

There is already a `codebook` package with add-ins.

**Comment by briatte** [comment]
@larmarange Sure, let's have both names for retro-compatibility.

I don't know `codebook`, but it looks alright!
