### ISSUE TITLE
Improving syntax generated by add-ins

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#104]
Hi,

this just a small details regarding the 3 add-ins.

The generated code could be slightly improved by following https://style.tidyverse.org, in particular spacing (cf. https://style.tidyverse.org/syntax.html#spacing) and long lines (https://style.tidyverse.org/syntax.html#long-lines).

Curent code:

```
hdv2003$age_rec <- cut(hdv2003$age, include.lowest=FALSE,  right=TRUE,
                       breaks=NULL)
``` 

Should be:

```
hdv2003$age_rec <- cut(
  hdv2003$age, 
  include.lowest = FALSE,  
  right = TRUE,
  breaks = NULL
)
``` 

It would be a nice way to show good practices.

**Comment by juba** [comment]
Yes, good point.

I just improved the generated code styling for the three addins by adding line breaks and passing the code to `styler::style_text`. I hope the output is fine.

Thanks for the suggestion !
