### ISSUE TITLE
error produced by freq() when a character vector contains both "NA" and NA

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#106]
The following works perfectly:

```r
freq(c("A", "B", "NA"))
freq(c("A", "B", NA))
```

but if the vector contains both `"NA"` and `NA`, there is an error:

```r
freq(c("A", "B", "NA", NA))
```

It seems that the error comes from that line of code:

```r
rownames(result) <- ifelse(is.na(names(tab)), "NA", names(tab))
```

**Comment by juba** [comment]
Thanks for reporting ! This should be fixed now.
