### ISSUE TITLE
add-in Levels recoding with dplyr::recode()

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#107]
When recoding with `dplyr::recode()`, and if we want to get a factor, as `dplyr::recode()` produce a character vector, the add-in currently add a call to `factor()`.

However, in such case, it would be better to use directly `dplyr::recode_factor()`.

Regards

**Comment by juba** [comment]
I tend to use `fct_recode` for recodings and thus I didn't knew about `recode_factor`. Thanks for pointing this out, it should be fixed in the development version.
