### ISSUE TITLE
Breaking changes to questionr resulting from janitor 2.0.0

### ISSUE THREAD

**Issue by sfirke** [juba/questionr#108]
Hi -

I am putting the finishing touches on janitor 2.0.0, which is going to CRAN soon (they are asking for it because of changes to R 4.0.0, dplyr 1.0.0, tibble 3.0.0).  I ran a revdepcheck now that the big stuff is merged in and it found new errors in questionr as a result.  I changed the `adorn_` functions but didn't expect it to change much for downstream packages.

Here is the failure log:
```
- 1. Failure: prop, cprop and lprop tabyl versions are correct (@test_tables.R#
ltabl$Freq not equal to ltab$Freq.
18/27 mismatches
x[1]: "52.7"
y[1]: "47.3"

x[2]: "21.6"
y[2]: "78.4"

x[3]: "23.3"
y[3]: "76.7"

x[4]: "45.0"
y[4]: "55.0"

x[5]: "44.2"
y[5]: "55.8"

-- 2. Failure: prop, cprop and lprop tabyl versions are correct (@test_tables.R#
ctabl$Freq not equal to ctab$Freq.
25/27 mismatches
x[1]: "9.7"
y[1]: "10.7"

x[2]: "5.7"
y[2]: "25.5"

x[3]: "1.8"
y[3]: "7.3"

x[4]: "6.5"
y[4]: "9.8"

x[5]: "10.4"
y[5]: "16.1"

-- 3. Failure: prop, cprop and lprop tabyl versions are correct (@test_tables.R#
tabl$Freq not equal to tab$Freq.
27/27 mismatches
x[1]: "5.35"
y[1]: "4.80"

x[2]: "3.15"
y[2]: "11.45"

x[3]: "1.00"
y[3]: "3.30"

x[4]: "3.60"
y[4]: "4.40"

x[5]: "5.75"
y[5]: "7.25"

== testthat results  ===========================================================
[ OK: 43 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 3 ]
1. Failure: prop, cprop and lprop tabyl versions are correct (@test_tables.R#98) 
2. Failure: prop, cprop and lprop tabyl versions are correct (@test_tables.R#110) 
3. Failure: prop, cprop and lprop tabyl versions are correct (@test_tables.R#122) 

Error: testthat unit tests failed
Execution halted
```

I could try to clone questionr and see if I can find the error and isolate & patch it with a PR.  But if you're up for it, it might be most efficient for you to get the latest version of janitor via `devtools::install_github("sfirke/janitor")` and then run your tests locally to see what is going on.

Sorry for any inconvenience this causes.  The changes to janitor 2.0.0 are in the repo's NEWS file if you're interested.

Thanks,
Sam

**Comment by sfirke** [comment]
You can hold off for now, I think this is a problem on my end.  To explain the above, in a 2-way tabyl the column order of a factor variable seems to be spread in the reverse order -- so in the tests above, the tabyl version now is ordered femme, homme rather than the other way around.  I didn't mean to introduce that change and am working on isolating it.

So ignore for now and I can close when I solve this.

**Comment by sfirke** [comment]
Indeed, I changed only a single line in `tabyl` to be compatible with tibble 3.0.0 release -- and it broke this behavior.  I didn't have a test but luckily you did!  Saved this error from going to CRAN.  Thanks and sorry for the false alarm! 🙏

**Comment by juba** [comment]
I didn't even had the time to answer to your first message before you fixed it :-)

Many thanks for doing a revdep check and solving the issue, I'm glad this had been useful to track a small bug !

Thanks !
