### ISSUE TITLE
Create an interactive variable dictionary

### ISSUE THREAD

**Issue by juba** [juba/questionr#11]
Idea : create a shiny interface for a variable dictionary. Possible features : interactive search in variable names / variables labels (`lookfor`), `summary`, etc.

**Comment by larmarange** [comment]
By the way, `codebook` is now proposing such functionality: https://rubenarslan.github.io/codebook/index.html

They propose an interactive version (but you can work in the console) and a static version (allowing to continue to work in the console).

So, should this issue still be open? We could consider that codebook is enough.

Or we could implement something similar based on `look_for()`

**Comment by juba** [comment]
Yep, you're right, we can close this one too. No reason to reinvent the wheel.

Thanks for the `codebook` reference, I didn't know of this package.
