### ISSUE TITLE
irec, icut et iorder n'aiment pas les objets avec des noms de fonctions

### ISSUE THREAD

**Issue by nalimilan** [juba/questionr#113]
Je viens de tomber sur un petit bug idiot, qui m'a quand même occupé un moment: `irec`, `icut` et `iorder` ne marchent pas avec des jeux de données qui ont des noms de fonctions fournies par R ou des paquets. J'avais appelé une table `rep` (pour « répondant »), et elle n'apparaît pas dans la liste des jeux de données. Si on la passe explicitement avec `irec(rep)`, elle ne s'affiche pas non plus.

Je soupçonne l'expression `inherits(get(x, envir = sys.parent()), "data.frame")` d'être à l'origine de ça. Peut-être qu'il faudrait appeler `sys.parent()` depuis le premier niveau de `irec`, le stocker dans un object, et le réutiliser dans cette fonction anonyme? Les environnements, c'est un des trucs les plus flippants de R...

(Bon, je sais, c'est sans doute pas une bonne idée d'utiliser des noms de fonctions pour mes jeux de données. Mais R l'autorise, alors... :-)

**Comment by juba** [comment]
Ah non mais ça arrive souvent de donner des noms de fonction à des objets, ça m'arrive tout le temps !

Normalement ça devrait être réglé, j'ai juste remplacer les `sys.parent()` par des `.GlobalEnv`, de toutes façons ces fonctions ne peuvent être appelées que depuis une session interactive... donc je ne pense pas que ça pose de problème.

Merci d'avoir pris le temps de remonter le problème !

**Comment by nalimilan** [comment]
Merci!
