### ISSUE TITLE
Bugs in irec()?

### ISSUE THREAD

**Issue by matthias-studer** [juba/questionr#115]
Dear Developers, 

First of all, thank you for questionr! I am planning to use the recoding add-ins in my classroom. I am sure that the students will love it. I only noticed two potential issues.
  —If dplyr or forcats are not loaded (using library) there is an error message when using the corresponding recode functions. I think that this could be easily fixed by loading the package if available or removing the possibility if not. 
  —When using irec() for the first time, the R.cache package asks about the creation of a temporary directory in AppData\Local\R\R.cache. This blocks the irec window. You can reproduce it by removing the AppData\Local\R\R.cache folder. This is probably not a critical issue as it only occurs once, but it might trigger questions from less technology inclined students. 

All the best and thanks again!
Matthias

**Comment by juba** [comment]
Hi, and thanks for your feedback !

Regarding the error message about `dplyr` or `forcats`, it is intentional as you may launch `irec` without having loaded the package but still want to generate the code. And to check if the packages are installed at each `irec` launch would be a bit overkill and slow down its startup...

Regarding R.cache, I wasn't aware of the problem but I can reproduce it, I'll take a look at it, thanks for taking the time to report the issue.

**Comment by juba** [comment]
Sorry, I think I misunderstood your first point. Indeed, if forcats or dplyr are installed, they are considered as loaded by `irec` even if not explicitly loaded with `library`. And this gives an error message in the last `irec` tab.

I'll take a look at it, sorry for the misunderstanding.

**Comment by juba** [comment]
Ok, so I think the two problems may be solved in the development version : 

- styler caching is deactivated in `irec`, `icut` and `iorder` to avoid the blocking R.cache message at first launch
- I use another method to detect if `dplyr` or `forcats` are loaded, which should avoid them to be selected by default if not explicitly called with `library`

Let me know if these are really the issues you were thinking of, and if they seem fixed for you too.

Thanks !

**Comment by matthias-studer** [comment]
Thanks. The development version looks great! 

I think that it was a great idea to add an error message if the corrected package is not loaded. I think this is exactly what (lost) students would like to have.

**Comment by juba** [comment]
Just for information, as you plan to use `irec`, I just saw that `dpyr::recode` is in "suestioning" lifecycle, so I may remove it or replace it with `dplyr::recode_factor` soon.

Thanks again for your report.
