### ISSUE TITLE
Utiliser fct_relevel pour réordonner les modalités d'un facteur

### ISSUE THREAD

**Issue by nalimilan** [juba/questionr#118]
Le greffon de réordonnancement interactif génère du code qui utilise `factor(x, levels=...)`. Ça marche très bien, mais je trouve que cette méthode est un peu risquée pour des étudiant.es, puisque si on oublie une modalité elle est éliminée sans avertissement. Est-ce qu'il ne vaudrait pas mieux utiliser `fct_relevel` si forcats est chargé?

(D'ailleurs ça me désespère qu'on ne puisse pas se contenter de manuellement changer l'ordre des arguments à `fct_recode`, mais c'est un autre problème (https://github.com/tidyverse/forcats/issues/45)).

**Comment by juba** [comment]
Yep, excellente idée. Je viens de l'implémenter dans la version de dev, n'hésite pas à me signaler si tu as l'occasion de tester.

Merci pour la suggestion !

**Comment by nalimilan** [comment]
Nickel, merci ! Je viens de tester, ça marche chez moi.
