### ISSUE TITLE
Découpage interactif avec des années

### ISSUE THREAD

**Issue by nalimilan** [juba/questionr#119]
La fonction `cut` fonctionne assez mal par défaut avec les années : les libellés générés automatiquement sont du style `(1.95e+03,1.96e+03]` au lieu de `(1950,1960]`. Pour obtenir un résultat raisonnable, il faut passer `dig.lab=4` manuellement. Est-ce que ça vaudrait le coup de proposer cette option dans le greffon de découpage interactif?

Une autre possibilité serait d'avoir un menu déroulant avec plusieurs styles de libellés. Ça permettrait de proposer aussi le plus classique `1951-1960`. 

(Au fait, je trouve que `right=TRUE` est une très mauvaise valeur par défaut, je ne sais pas pourquoi R l'a choisi, mais `Hmisc::cut2` a pris l'option inverse, qui donne `1950-1959`, ce qui est plus standard. Peut-être que questionr pourrait prendre la liberté d'utiliser `right=FALSE` par défaut.)

**Comment by juba** [comment]
Alors, je suis assez d'accord pour le `right = TRUE` par défaut et pour rajouter une option `dig.lab` (avec une valeur par défaut de 4 ?). Par contre pour proposer plusieurs styles de libellés ça me semble déjà plus de boulot...

**Comment by nalimilan** [comment]
Je dois dire que j'ai pas du tout considéré la question de la difficulté à coder ça. :-)

`dig.lab=4` semble raisonnable par défaut, ça a l'avantage de couvrir les dates (`cut` utilise 3).

**Comment by juba** [comment]
Hop, normalement on devrait avoir right=FALSE + un champ pour dig.lab à 4 par défaut.

Je t'avoue que pour les styles de labels ça me semble effectivement un peu complexe... Il faudrait le faire à coup de regexp sur les labels générés par défaut je dirais, mais c'est pas très satisfaisant.

**Comment by juba** [comment]
Bon du coup je ferme l'issue pour le moment parce que ça ne me semble pas trivial du tout cette histoire de labels "custom". N'hésite pas à relancer si besoin.
