### ISSUE TITLE
error message styler

### ISSUE THREAD

**Issue by guillaume7986** [juba/questionr#121]
Hi, these is my error message
iorder(enqueteEcho, Sexe)
Erreur : .onLoad failed in loadNamespace() for 'styler', details:
  call: NULL
  error: package ‘backports’ does not have a namespace

I've got no idea to resolve, thank's

**Comment by juba** [comment]
I don't think this is related to questionr, but did you try to install the `backports` package manually ?

```r
install.packages("backports")
```

**Comment by guillaume7986** [comment]
Thanks a lot, it s work !

Le ven. 6 nov. 2020 à 22:15, Julien Barnier <notifications@github.com> a
écrit :
