### ISSUE TITLE
na.rm et na.show avec wtd.table

### ISSUE THREAD

**Issue by nalimilan** [juba/questionr#122]
Est-ce que l'argument `na.rm` sert à quelque chose dans `wtd.table`? Comme `na.show=TRUE` appelle `addNA(x)` avant que `na.rm` ait son mot à dire, on dirait que ça ne change rien:
```R
> wtd.table(c(1, NA), weights=c(1, 1), na.show=TRUE, na.rm=TRUE)
   1 <NA> 
   1    1 

> wtd.table(c(1, NA), weights=c(1, 1), na.show=TRUE, na.rm=FALSE)
   1 <NA> 
   1    1 

> wtd.table(c(1, NA), weights=c(1, 1), na.show=FALSE, na.rm=FALSE)
1 
1 

> wtd.table(c(1, NA), weights=c(1, 1), na.show=FALSE, na.rm=TRUE)
1 
1 
```

Par simplicité, j'aurais tendance à préférer `na.rm`, pour ne pas rajouter des variations en plus de `useNA="always"`, `use="na.or.complete"`, etc. :-)

**Comment by juba** [comment]
Alors... Voilà une question qui revient de temps en temps et que je mets avidement sous le tapis :-)

Il est clair que `na.rm` et `na.show` ont été des mauvais choix dès le départ. La preuve en étant que je suis incapable de me rappeler leur fonctionnement, voire de le comprendre en lisant la doc. Il y a quand même une petite différence entre les deux, mais qui ne se voit que dans un tableau croisé et dans des conditions très particulières : 

> wtd.table(c("a", "b", NA), c("b","b","a"), weights=c(3, 2, 1), na.show=FALSE, na.rm=TRUE)
  b
a 3
b 2
> wtd.table(c("a", "b", NA), c("b","b","a"), weights=c(3, 2, 1), na.show=FALSE, na.rm=FALSE)
  a b
a 0 3
b 0 2

Bref, on est d'accord que ça ne va pas, mais je suis un peu bloqué si je ne veux pas risquer de casser du code existant...

**Comment by nalimilan** [comment]
Ah oui avec plusieurs variables effectivement c'est pas pareil. Mais c'est subtil. ;-)

Sinon une solution pour pas casser le code existant serait d'ajouter `useNA` comme dans `table` (ce qui aurait une certaine logique), et d'afficher un avertissement quand on utilise `na.show` et `na.rm`.

**Comment by juba** [comment]
Ah oui très bonne idée, merci !

Je viens de rajouter `useNA` dans la version de dev, mais il faut que je crée des tests pour rendre ça un peu plus robuste (j'aurais dû faire ça depuis longtemps).

En réécrivant le truc je me rends compte que l'interaction entre `na.rm` et `na.show` était buggée en fait.

**Comment by nalimilan** [comment]
Cool ! Une épine de moins pour présenter l'utilisation des pondérations.

Au fait, est-ce que t'as envisagé d'avoir une section sur les pondérations dans ton nouveau manuel ? Je dis pas que je vais écrire quelque chose rapidement, mais si j'ai l'occasion de noter des choses, je me dis que ça vaudrait le coup de mutualiser.

**Comment by juba** [comment]
Hmm non j'avais pas prévu a priori, mais c'est sûr que ça pourrait être utile. Joseph Larmarange a fait un chapitre là-dessus dans son bouquin en ligne : https://larmarange.github.io/analyse-R/donnees-ponderees.html

**Comment by nalimilan** [comment]
Ah oui c'est pas mal. Il faudrait aussi présenter srvyr, la corrélation, d'autres tests... Pas évident.

**Comment by juba** [comment]
Yep. De mon côté je ne travaille pas assez souvent avec des données pondérées pour me lancer là-dedans je crois (et pouvoir être utile).

Bon j'ai ajouté quelques tests, je vais fermer l'issue, n'hésite pas à la rouvrir en cas de besoin.
