### ISSUE TITLE
Easy ggplot2 from survey objects

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#123]
These last months I have tested a small helper to facilitate ggplot2 plots from a survey object.

The code is visible here: https://github.com/larmarange/JLutils/blob/master/R/ggsurvey.R

It extracts the underlying data.frame from the survey object, add weights to it and map the weights to the appropriate aesthetic.

Produced graphs are correct as long as they are purely descriptive. Graph implying the computation of variance or confidence intervals (like `geom_smooth()`) will not always be correct as only weights will be taken into account and not survey design. However, for 95% of graphs it is not a problem.

I do not know if such helper would be relevant for `questionr`. Let me know what you think.

Regards

**Comment by juba** [comment]
Hmm the function is interesting but the downside I see in including it in questionr is that (if I'm not mistaken) the package would then need to import both `ggplot2` and `survey`.

**Comment by larmarange** [comment]
No need to import `ggplot2` and `survey`. If I'm right, they could just be listed in Suggests, as long as we test their availability in the function.

**Comment by larmarange** [comment]
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages

**Comment by juba** [comment]
Yes, you're right, I'm always a bit confused between Imports, Depends and Suggests.

Well, if `ggplot2` and `survey` are in `Suggests` I see no objection not to include the function in `questionr` if you wish so.

**Comment by larmarange** [comment]
OK good. I will prepare a PR
