### ISSUE TITLE
Erreur avec questionr:::irec()

### ISSUE THREAD

**Issue by bourguignonmel** [juba/questionr#130]
Bonjour,
Depuis peu, lorsque je souhaite utiliser les addins pour faire un recodage via questionr, je reçois le message d'erreur suivant:
Erreur dans if (ifunc_run_as_addin()) { : 
  valeur manquante là où TRUE / FALSE est requis
Quelqu'un a déjà eu le cas et a trouvé une solution pour trouver d'où cela provient?
Merci d'avance et désolée pour le dérangement.

**Comment by juba** [comment]
Bonjour,

Est-ce que vous pourriez préciser de quelle manière vous lancer l'addin ? Depuis RStudio ou non, en passant par le menu *addins* ou en utilisant directement les fonctions dans la console ?

Par ailleurs est-ce que le package `rstudioapi` est installé sur votre système ?

**Comment by bourguignonmel** [comment]
Bonjour,
Je travaille dans RStudio et c'est en passant par le menu addins (pour avoir le détails de toutes les modalités de la variable). En entrant le code directement ca fonctionne normalement, j'ai pu faire mon recodage de cette façon. 
Je n'ai jamais utilisé le package rstudioapi mais peut-être s'installe-t-il par le biais d'autres packages?
Merci,

**Comment by juba** [comment]
C'est assez étrange. Quelles versions de R et RStudio utilisez-vous ? Si vous (ré)installez `rstudioapi` avec : 

```r
install.packages("rstudioapi")
```

Est-ce que ça change quelque chose ?

**Comment by bourguignonmel** [comment]
Bonsoir, 

En tapant questionr::ifunc_run_as_addin(), j'obtiens le code erreur suivant: Erreur : 'ifunc_run_as_addin' n’est un object exporté depuis 'namespace:questionr'.

Par contre, en ayant installé le package rstudioapi, j'arrive à nouveau à utiliser les addins (je venais de faire un nouveau test avant ces tentatives qui débouchait encore sur le même message d'erreur qu'hier). Je ne sais pas si la résolution du problème est liée à l'installation de rstudioapi mais à présent ça fonctionne correctement. 

Merci!

**Comment by juba** [comment]
Alors effectivement je pense que le problème venait de là (du package `rstudioapi`). Très content si c'est résolu en tous cas !

**Comment by bourguignonmel** [comment]
Merci beaucoup pour votre aide.
