### ISSUE TITLE
Level recoding

### ISSUE THREAD

**Issue by AurelienDasre** [juba/questionr#132]
Bonjour,

Certains de mes étudiants rencontrent un problème depuis la mise à jour du package questionR. 

Dès qu’on veut recoller une variable, on tombe sur le message de la photo ci-jointe
![IMG_6781](https://user-images.githubusercontent.com/98756538/151813208-a9fc011c-0149-4a8b-bbb0-216ac919c6e1.jpg)

Avez-vous une idée de la façon de résoudre de problème?

Merci d'avance.

Bien cordialement.

Aurélien Dasré.

**Comment by juba** [comment]
Oui je suis désolé, c'était effectivement un bug (cf. #131) dans la dernière version lors du recodage de variables numériques.

En étant qu'une nouvelle version soit mise sur le CRAn, le plus simple est d'installer la version de développement avec :

```r
options(repos = c(
  juba = 'https://juba.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

install.packages('questionr')
```

Désolé pour les désagréments occasionnés...

**Comment by juba** [comment]
La version 0.7.7 qui corrige ce problème vient d'être acceptée sur le CRAN. Mais il faut compter encore quelques jours avant notamment que la version Windows soit disponible.

Je ferme l'issue pour le moment, n'hésitez pas à la rouvrir si nécessaire.

**Comment by AurelienDasre** [comment]
Merci!
