### ISSUE TITLE
error in factor ordering and recoding when colnames starts with a number

### ISSUE THREAD

**Issue by bassam-abulnoor** [juba/questionr#133]
Hello :)
When colnames starts with a number both shiny functions return an error as displayed in the pictures. Thanks in advance :)

 
![A](https://user-images.githubusercontent.com/51817217/152333809-b268016c-365a-448a-b09b-5f3dc1453ad8.png)

![B](https://user-images.githubusercontent.com/51817217/152333824-8a2c5d15-012b-49d3-b5f2-0e0f683037c3.png)

**Comment by juba** [comment]
Yes, you're right, I did check for presence of spaces in variable names, but for other invalid cases. This should now be fixed in the development version.

Thanks for reporting the issue !

**Comment by bassam-abulnoor** [comment]
you're welcome
