### ISSUE TITLE
Problème d'installation du package questionr

### ISSUE THREAD

**Issue by 2502Sociologue** [juba/questionr#134]
bonjour, 
Je vous écrit parce que je rencontre des difficultés avec le package questionr. j'ai un nouveau pc version Windows 11. je vous mets en copie les messages d'erreur que je reçois afin que vous puissiez m'aider à résoudre ce problème. 

Installation du package 

(car ‘lib’ n'est pas spécifié)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/questionr_0.7.7.zip'
Content type 'application/zip' length 3889467 bytes (3.7 MB)
downloaded 3.7 MB

package ‘questionr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\33762\AppData\Local\Temp\RtmpsTKwgm\downloaded_packages

Error: le chargement du package ou de l'espace de noms a échoué pour ‘questionr’ in library.dynam(lib, package, package.lib) :
La DLL ‘promises’ est introuvable : elle n'est peut-être pas installée pour cette architecture ?

**Comment by juba** [comment]
Est-ce que vous pouvez essayer de réinstaller le package "promises" pour voir si ça résoud le problème ?

```r
install.packages("promises")
```

**Comment by 2502Sociologue** [comment]
Je viens de le faire

**Comment by juba** [comment]
Et cela résoud-il le problème ? Vous avez toujours le même message au moment de faire `library(questionr)` ?

**Comment by 2502Sociologue** [comment]
package ‘promises’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot delete reparse point 'C:\Users\33762\OneDrive - Université paris nanterre\Documents\R\win-library\4.1/promises/libs', reason 'La balise spécifiée dans la requête et celle présente dans le point d'analyse ne correspondent pas'
Warning in install.packages :
  cannot remove prior installation of package ‘promises’
Warning in install.packages :
  cannot delete reparse point 'C:\Users\33762\OneDrive - Université paris nanterre\Documents\R\win-library\4.1/promises/libs', reason 'La balise spécifiée dans la requête et celle présente dans le point d'analyse ne correspondent pas'
Warning in install.packages :
  restored ‘promises’

The downloaded binary packages are in
	C:\Users\33762\AppData\Local\Temp\RtmpsTKwgm\downloaded_packages
> library(promises)
Error: le package ‘promises’ n'a pas été installé pour 'arch = x64'

**Comment by juba** [comment]
Ah, je vois, le problème vient sans doute du fait que votre bibliothèque d'extensions R est installée dans un dossier synchronisé par OneDrive, ce qui pose souvent problème.

Pour le coup le problème n'est pas lié à `questionr`, mais peut-être que la solution suivante peut aider à le résoudre ?

https://mattwthomas.com/blog/r-fix-onedrive/
