### ISSUE TITLE
Remove Linux requirement

### ISSUE THREAD

**Issue by barracuda156** [juba/questionr#136]
`xclip` is available on multiple platforms, including macOS and other variants of Unix. Requiring Linux is misleading.
I have just built `questionr` on MacOS, and it passes all tests.

```
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: powerpc-apple-darwin10.8.0 (32-bit)

> library(testthat)
> library(questionr)

Attaching package: 'questionr'

The following object is masked from 'package:testthat':

    describe

> 
> test_check("questionr")
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 67 ]
> 
> proc.time()
   user  system elapsed 
 10.691   0.331  10.950 
```

**Comment by juba** [comment]
On macOS `pbcopy` is used to access the clipboard, so `xclip` is only needed on Linux.

**Comment by barracuda156** [comment]
> On macOS `pbcopy` is used to access the clipboard, so `xclip` is only needed on Linux.

Ah, okay, got it. Thank you for clarifying.

**Comment by juba** [comment]
No problem, thanks for taking the time to report the issue.
