### ISSUE TITLE
`wtd.table` ne marche pas avec des vecteurs `labelled`

### ISSUE THREAD

**Issue by nalimilan** [juba/questionr#137]
Je viens de tomber sur cette erreur en travaillant sur une enquête :
```R
> wtd.table(haven::labelled(1:10), weights=1:10)
Erreur dans proxy[, ..., drop = FALSE] : nombre de dimensions incorrect
```

Est-ce que le bug viendrait de haven?
```R
> haven::labelled(1:10)[1, drop=FALSE]
Erreur dans proxy[, ..., drop = FALSE] : nombre de dimensions incorrect
```

**Comment by juba** [comment]
Désolé pour le délai de la réponse, j'étais passé à côté de l'issue.

Effectivement, `wtd.table` ne fonctionne pas avec des objets `haven::labelled` quand `useNA` est égal à `"no"` (la valeur par défaut) ou que `exclude` n'est pas `NULL`, et c'est lié au fait que les objets `labelled` ne semblent pas gérer l'argument supplémentaire `drop = FALSE` lors des opérations de sélection.

Je pense que le plus simple pour régler le problème est de convertir ces objets en `factor` avant utilisation de `wtd.table`.

Merci d'avoir pris le temps de signaler le problème.
