### ISSUE TITLE
memisc compatibility??

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#26]
Not a precise point but rather a general discussion.

Do you use the `memisc` package? It's a way to store more information about variables, labels and missing codes but I'm also reluctant to use data.set instead of proper data.frame as therefore some functions could not be used directly.

For me, a good way would to be able to use a data.set in the same way I'm using a data.frame. Some functions in `questionr` could not be used directly with a data.set (for example `freq`) but adding compatibility would be easy. 

So, it's more a general discussion, do you think that compatibility with `memisc data.set` should be done when possible within `questionr` or is it not important for `questionr`?

**Comment by larmarange** [comment]
`data.set` are not so easy to deal with. Now with `haven` there is some work on-going in different packages to deal with variable and value labels as imported by this package.

Strategically, it would be maybe more interesting to try to develop compatibility with `haven` rather than `memisc`.  Could I suggest to close that issue?

**Comment by briatte** [comment]
I agree. `memisc` is too much to deal with. Supporting `haven` would be great!
