### ISSUE TITLE
Calcul de l'âge

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#45]
Le calcul d'un âge (différence entre deux dates) n'est pas une tâche si facile si l'on souhaite le faire proprement. Par défaut, R calcule les différentes entre deux dates en nombre de jours. Une division par 365.25 n'est pas l'approche la plus pertinente.

Il existe une fonction faisant ce calcul proprement : https://github.com/jknowles/eeptools/blob/master/R/age_calc.R

Elle est fournit dans un package (epptools) qui a de nombreuses dépendances. Dès lors, il n'est pas forcément très approprié de charger epptools juste pour cette fonction.

Je me demandais si cette fonction n'aurait pas vocation à intégrer questionr, avec quelques petites modifications :
- être appelée tout simplement `age`
- avoir les années comme unité par défaut

Qu'en pensez vous ?

**Comment by larmarange** [comment]
Pour ceux que ça intéresse, une petite présentation de comment calculer des âges sous R:

http://joseph.larmarange.net/?Calculer-proprement-un-age-sous-R

**Comment by juba** [comment]
Excellent pour la méthode `time_length`, elle est bien mieux à sa place dans `lubridate` que dans `questionr`. Et merci pour la présentation sur les âges, ça fait une ressource claire et complète pour quiconque aurait des interrogations sur le sujet.
