### ISSUE TITLE
Take into account haven import in lookfor

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#47]
When importing SPSS/Stata files with haven, variable labels are stored as an attribute of each column.

We should take it into account in `lookfor`

**Comment by briatte** [comment]
I agree, `lookfor` and similar functions should work with `haven` labels. See also [this new package](https://strengejacke.wordpress.com/2015/05/22/sjmisc-package-for-working-with-labelled-data-rstats/), and `memisc` of course.

**Comment by larmarange** [comment]
Thanks. I didn't know `sjmisc`. Seems that a lot is happening around labels.

This week-end I was just exploring some functions for labelled frequency tables: https://github.com/larmarange/JLutils/blob/master/R/label_freq.R

**Comment by larmarange** [comment]
Should we include `get_var_labels` and `get_val_labels` into `questionr` ? 

It will be easier to rewrite both `lookfor` and `describe` using these two fonctions (working with both `haven` and `foreign`).

In addition, we could add a function `codebook` that will display both variable and value labels.

**Comment by larmarange** [comment]
Two additional questions @briatte :

* do we need to keep compatibility with `memisc` for lookfor?
* what is supposed the difference between `lookfor` and `describe`?

**Comment by larmarange** [comment]
You can find a pull request with inclusion of `get_var_labels` and `get_val_labels` and following, some changes in `describe` and `lookfor` now compatible with `haven`

**Comment by larmarange** [comment]
It could be easy to add value labels for `lookfor` : simply an additional col with the result of `paste(get_val_labels(data$var, "p"), collapse = " ")` applied to each variable.

**Comment by larmarange** [comment]
cf. Pull Request https://github.com/juba/questionr/pull/57

**Comment by larmarange** [comment]
cf. https://github.com/juba/questionr/pull/72
