### ISSUE TITLE
Tester les packages requis pour un projet

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#50]
Faisant suite à https://github.com/larmarange/analyse-R/pull/35, je me demande si ca ne vaudrait pas le coup d'ajouter une fonction à questionr pour détecter tous les packages appelés dans le cadre d'un projet (i.e. fichiers .R, .r,  .Rmd, .rmd, .Rhtml, .rhtml, .rnw, .Rnw, .snw, .Snw, exploration du working directory et de ses sous-répertoires) et installation le cas échéant des packages manquants ?

**Comment by juba** [comment]
Pourquoi pas ?
Ça serait une adaptation directe du script : 
https://github.com/larmarange/analyse-R/blob/gh-pages/verification_installation_dependances.R ?

**Comment by larmarange** [comment]
Oui c'est ça, sur cette base du code de @briatte

**Comment by juba** [comment]
Ben pas de problème. Juste un détail : dans la mesure du possible, ne pas oublier de passer les messages et autres chaînes de caractères traduisibles via `gettext()` (et mettre à jour le fichier `.po` du coup).

**Comment by larmarange** [comment]
Je regarde ça dans les prochains jours.

**Comment by larmarange** [comment]
Il semble qu'il y ait un package en développement sur ce sujet https://github.com/r-hub/sysreqs

**Comment by larmarange** [comment]
Fermer le ticket ici ?

**Comment by juba** [comment]
Si r-hub bosse dessus et au bout de 5 ans, je pense qu'on peut raisonnablement fermer le ticket :-)

**Comment by larmarange** [comment]
https://github.com/hadley/requirements

**Comment by briatte** [comment]
Je passe juste pour dire que je vois de plus en plus souvent `questionr` partout dans les scripts qui analysent des enquêtes. Le package est devenu un package requis dans plein d'endroits :-)

_Hope you're both good despite the times!_

**Comment by juba** [comment]
Hello !

C'est marrant parce que je pensais qu'entre le manque de développement, la quasi-absence de documentation et l'émergence de multiples alternatives plus modernes `questionr` serait en perte de vitesse mais ça n'a effectivement pas l'air d'être le cas. En tous cas le nombre de téléchargements est stable (même si une grosse partie semble venir d'une dépendance de `klaR`).
