### ISSUE TITLE
Value labels in freq

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#52]
Following https://github.com/juba/questionr/issues/47 and https://github.com/juba/questionr/pull/51 and the inclusion of `get_var_labels` and `get_val_labels`, I would like to create a function `to_factor` that take a vector and will return a factor.

If `x` is already a factor, it will return directly `x`.
If not, it will convert `x` to a factor. If some of the values found in `x` have a value label, then the label will be used. If not, value will be used. The idea is that we don't need to know in advance in labels exits or not, nor to check that all values have a label.

I'm also thinking of an option with 3 possibilities:

* "p" i.e. prefix, labels will be like "[1] Femmes"
* "l" i.e. labels, labels of the factor will be like "Femmes"
* "v" i.e. values, labels of the factor will be like "1"

With this function, it will be easy to modify `freq` and simply to apply `to_factor` to `x` at the beginning.

What do you think?

**Comment by briatte** [comment]
I like the idea very much, because I often find myself doing this by hand, using padded numbers e.g. 01, 02, etc. Not sure how to go with the implementation.

**Comment by larmarange** [comment]
Easy to implement once we have `get_val_labels`.

I will propose something this afternoon

**Comment by larmarange** [comment]
cf. https://github.com/larmarange/questionr/commit/15d1e7f1122609e582d2020d248d89b24449b209

Part of https://github.com/juba/questionr/pulls

**Comment by larmarange** [comment]
cf. Pull Request https://github.com/juba/questionr/pull/57

**Comment by larmarange** [comment]
cf. https://github.com/juba/questionr/pull/72
