### ISSUE TITLE
a labelled data set

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#55]
I have prepared a labelled data set based on a demographic survey with 3 data.frame:
* menages
* femmes
* enfants

It's appropriate for examples for `freq`, `ltabs` or `describe` and could be used for learning how to merge tables.

Would it be appropriate to add it to `questionr`?

**Comment by juba** [comment]
More datasets is always better, and I'm a bit tired of `rp99` and `hdv2003`. Is it possible to provide a multi data.frame dataset via data ? Or do you have to create 3 different datasets ?

**Comment by larmarange** [comment]
As you provide a .Rdata it's possible to provide 3 data.frame in one call
of data

 Joseph

2015-07-06 18:04 GMT+02:00 Julien Barnier <notifications@github.com>:

**Comment by juba** [comment]
Great. No problem for a new dataset, then.

**Comment by briatte** [comment]
I like the idea, as long as `questionr` offers both unlabelled and labelled data examples.

**Comment by larmarange** [comment]
OK I will had it to the pull request.

The purpose was never to replaces the existing datasets. ;-) The idea is much more to provide more examples of what is possible now.

**Comment by juba** [comment]
Thanks ! Would it be possible to create a separate pull request ? I find "mega" PR more difficult to review and understand...

**Comment by larmarange** [comment]
Yeah will try to do so

**Comment by larmarange** [comment]
And a dedicated pull request https://github.com/juba/questionr/pull/56
