### ISSUE TITLE
multiplot in questionr?

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#61]
Should the `multiplot` function (proposed here http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/) be included in `questionr`?

**Comment by briatte** [comment]
It should really be in `ggplot2`…

**Comment by larmarange** [comment]
I just opened an issue on ggplot2 repository

**Comment by larmarange** [comment]
We have the answer:

> I think arranging multiple plots on a page is outside of the scope of ggplot2.

https://github.com/hadley/ggplot2/issues/1167#issuecomment-123372615

**Comment by juba** [comment]
I'm not sure I would include this in `questionr`. First it seems a bit out of the package scope, and we would have to check with the function author to get its agreement (there's no visible License for this code).

I'm closing this issue, but feel free to reopen it if you disagre.
