### ISSUE TITLE
données labellisées en anglais

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#62]
Le set `fecondite` permets de montrer ce que sont des données labellisées. Seul souci c'est en français. Je donne quelques cours en anglais en ce moment et je vais très probablement en faire une version anglaise  (renommage des noms des data frames, des noms des variables et des étiquettes).

Est-ce que ca vaut le coup d'inclure également dans `questionr` ce set `fertility` ?

**Comment by juba** [comment]
Yes, why not ?
