### ISSUE TITLE
Fonctions diverses

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#63]
J'ai quelques fonctions prêtes à l'emploi dans **JLutils** (mon package fourre-tout) et que j'utilise au quotidien. Je me demande si certaines n'auraient pas vocation à rejoindre **questionr**.

## Une série de formateurs

Pour la réalisation de graphiques, il est important de mettre en forme les axes correctement (nombre de décimales, affichage en pourcent, séparateurs de milliers). De même lorsque lorsque l'on affiche des résultats au propre dans un rapport R markdown.

Par ailleurs, la mise en forme diffère entre l'anglais et le français (virgule pour séparer les décimales en français et espace avec le symbole %).

https://github.com/larmarange/JLutils/blob/master/R/formating.R contient toute une série de fonctions prêtes à l'emploi couvrant la plupart des usages courants. Quelques exemples :

```
> fr0(123456.789)
[1] "123 457"
> fr2(123456.789)
[1] "123 456,79"
> en2(123456.789)
[1] "123'456.79"
> int2(123456.789)
[1] "123 456.79"
> pourcent1(0.123456)
[1] "12,3 %"
> pourcent3(0.123456)
[1] "12,346 %"
> percent2(0.123456)
[1] "12.35%"
> comp.percent1(0.123)
[1] "87.7%"
> comp.pourcent0(0.123)
[1] "88 %"
> comp.pourcent1(0.123)
[1] "87,7 %"
```

Le chiffre en suffixe indique le nombre de décimales (il y a aussi toujours une version générique où le nombre de décimales est passé en argment).

- les fonctions `fr` pour un affichage à la française
- les fonctions `en` pour un affichage à l'anglaise (avec des ' commes séparateurs de décimales)
- les fonctions `int` pour un affichage dit international demandé par certaines revues (espace pour les milliers, point pour les décimales. En passant, la revue Lancet recommande pour sa part un middle point comme séparateur de décimales. Une version à rajouter ?)
- `percent` pour les pourcentages en anglais
- `pourcent`pour les pourcentages en français
-  `comp.pourcent` et `comp.percent` pour les compléments à un

Il n'y a pas de "pour mille"  pour le moment mais on peut discuter son rajout.

## Arrondi OMS

C'est peut être accessoire pour `questionr`. L'OMS a une règle d'arrondi un peu particulière :

> In WHO publications, population numbers are usually presented as follow:
>
> - 0 if < 5
> - 10 if ≥ 5 and < 10
> - one significant digit if ≥ 10 and < 100
> - two significant digits if ≥ 100 and < 10 millions
> - three significant digits if ≥ 10 millions

```
> who.format(c(3, 8, 42, 75, 45678, 9876543, 12345678))
[1] "         0" "        10" "        40" "        80" "    46 000" " 9 900 000" "12 300 000"
```

## Opérateur %p% pour concaténer du texte

La fonction `paste` sert assez souvent dès qu'on fait des graphiques programmatiques ou des rapports automatisés. `x %p% y` est l'équivalent de `paste0(x, y)`. C'est plus lisible et plus rapide à écrire.

cf. https://github.com/larmarange/JLutils/blob/master/R/concatenate.R

## Intervalles de confiance d'une proportion

https://github.com/larmarange/JLutils/blob/master/R/prop.ci.R

Des wrappers pour `prop.test` pour récupérer facilement des intervalles de confiance d'une proportion.

```
> freq(d$sport)
       n    % val%
Non 1277 63.8 63.8
Oui  723 36.1 36.1
NA     0  0.0   NA
> prop.ci(d$sport)
[1] 0.6169447 0.6595179
> prop.ci.lower(d$sport)
[1] 0.6169447
> prop.ci.upper(d$sport)
[1] 0.6595179
> prop.ci(d$sport, conf.level = 0.9)
[1] 0.6204011 0.6562194
> prop.ci(table(d$sport))
[1] 0.6169447 0.6595179
> prop.ci(d$sport=="Non")
[1] 0.6169447 0.6595179
> prop.ci(d$sport=="Oui")
[1] 0.3404821 0.3830553
> 
> prop.ci.lower(c(1277, 723), n = 2000)
[1] 0.6169447 0.3404821
> prop.ci.upper(c(1277, 723), n = 2000)
[1] 0.6595179 0.3830553
```

Très utile par exemple pour des aggrégations, pour préparer les données d'un graphique. Exemple :

```
> d <- as.data.table(d)
> res <- d[,.(freq=.N),by=.(sexe,sport)]
> res[, n := sum(freq), by=sexe]
> res[, prop := freq/n]
> res[, prop.l := prop.ci.lower(freq, n)]
> res[, prop.h := prop.ci.upper(freq, n)]
> res
    sexe sport freq    n      prop    prop.l    prop.h
1: Femme   Non  747 1101 0.6784741 0.6498433 0.7058435
2: Femme   Oui  354 1101 0.3215259 0.2941565 0.3501567
3: Homme   Oui  369  899 0.4104561 0.3782002 0.4434870
4: Homme   Non  530  899 0.5895439 0.5565130 0.6217998
```

Bref, si des fonctions vous semblent relever de **questionr**, pas de souci pour les y transférer. Sinon, ça restera dans le "foure-tout";

Cdlt

**Comment by briatte** [comment]
:+1: `prop.ci`

Pour les formateurs, je ne sais pas ; il y a presque de quoi faire un package juste avec ça, notament si tu rajoutes des fonctions basiques de _cleanup_, comme par exemple "retirer les `%`" (`gsub("%", "", x)`).

Pour la concaténation, j'aime bien l'idée ; tu pourrais aller plus loin :

```{r}
> # concaténation
> `%+%` <- function(x, y) { paste0(x, y) }
> "a" %+% "b"
[1] "ab"
> # concaténation avec espace
> `%++%` <- function(x, y) { paste(x, y) }
> "a" %++% "b"
[1] "a b"
> # réplication
> `%*%` <- function(x, n) { rep(x, n) }
> "a" %*% 3
[1] "a" "a" "a"
> # réplication et concaténation
> `%**%` <- function(x, n) { paste0(rep(x, n), collapse = "") }
> "a" %**% 3
[1] "aaa"
> # séparation
> `%/%` <- function(x, y) { unlist(strsplit(x, y)) } 
> "a/b/c" %/% "/"
[1] "a" "b" "c"
```

Je ne sais pas si `questionr` doit héberger ces fonctions.

**Comment by larmarange** [comment]
Ces opérateurs de concaténation avancé auraient leur place dans `stringr` non?

Tu devrai sfair eune pull request LOL

**Comment by larmarange** [comment]
En fait, plutôt dans **stringi**. En effet, il y a déjà un opérateur `%s+%`. Il s'agirait juste d'étendre.

**Comment by juba** [comment]
Oula, je réponds plus que tardivement...

Alors, mon avis rapide et très en retard :

- pour les fonctions de formatage, pourquoi pas, par contre je préfèrerais n'avoir qu'une seule fonction et des arguments qui modifieraient la sortie. `who.format` pourrait d'ailleurs sans doute être incluse ?
- pour `prop.ci`, pourquoi pas également. Là aussi peut-être plutôt un argument genre `out="lower"` plutôt que trois fonctions différentes ?
- pour l'opérateur de concaténation j'aurais tendance à dire non, non pas que ça ne soit pas utile mais `questionr` ne me semble pas un package suffisamment "avancé" pour inclure des redéfinitions d'opérateurs de base...

**Comment by larmarange** [comment]
<quote>
pour les fonctions de formatage, pourquoi pas, par contre je préfèrerais n'avoir qu'une seule fonction et des arguments qui modifieraient la sortie. who.format pourrait d'ailleurs sans doute être incluse ?
</quote>

Le but original de ces fonctions est de pouvoir les utiliser directement avec `ggplot`, notamment pour mettre en forme les axes. Exemple :

```r
 scale_y_continuous(labels = percent)
```

Or dans ce cas, il faut donner un nom de fonction, sans possibilité de passer des arguments, d'où la multiplicité des fonctions proposées

**Comment by juba** [comment]
D'après cette réponse sur SO : https://stackoverflow.com/a/11471941/249691

Il semble qu'on peut faire quelque chose comme ça :

```r
foo <- function(n) { function(x, nb=n) return(round(x,nb)) }
scale_y_continuous(labels = foo(1))
scale_y_continuous(labels = foo(2))
```

**Comment by larmarange** [comment]
**Premier exemple**

```r
> qplot(cars$speed, cars$dist) + scale_y_continuous(labels=pourcent0)
```

Ca fonctionne car `pourcent0` (sans les parenthèses) renvoie une fonction.

**Exemple 2**

```r
> qplot(cars$speed, cars$dist) + scale_y_continuous(labels=pourcent(0))
Error in scale_labels.continuous(scale, major) : 
  Breaks and labels are different lengths
```

ne marche pas car `pourcent(0)``renvoie un nombre.


Dans ton exemple précédent, `foo` est une fonction qui renvoie une fonction. Mais du coup, on ne peut pas l'appliquer dans d'autres contexte. Par exemple, `foo(.024)` va me renvoyer une fonction, alors que `pourcent1(0.024)` va me renvoyer `2,4 %`, ce qui aujourd'hui peut aussi s'exprimer comme `pourcent(0.024, digits=1)`. Par contre, avec `foo`, on a une syntaxe du genre `foo(1)(0.024)`. Tout sauf intuitif pour l'utilisateur lambda.

Pour ma part, il m'arrive d'utiliser ces fonctions également en-dehors de ggplot, parfois sur une table, ou pour mettre en forme des nombres dans un document Rmarkdown.

Après, je comprens bien que multiplier les fonctions n'est pas optimum du point de vue du code, mais c'est beaucoup plus facile pour s'en souvenir, surtout pour des non codeurs.

**Comment by larmarange** [comment]
Pour `prop.ci` il y a déjà un paramètre `bounds = 1:2` où l'on peut choisir les deux, lower ou upper. Les fonctions `prop.ci.lower` et `prop.ci.upper` étaient proposées juste par convénience.

**Comment by juba** [comment]
On pourrait faire deux fonctions, une qui effectue le formatage proprement dit, et une autre qui serait un wrapper pour ggplot.

Quelque chose comme (non testé) :
```r
myformat <- function(x, type) {
  ...format things depending on type...
}

ggmyformat <- function(t) {
  function(x, type=t) myformat(x, type)
}
```
Du coup `myformat` pourrait être utilisé en ligne de commande, et le wrapper `ggmyformat` pour les `scales` de `ggplot2`.

J'ai tendance à penser qu'avoir une seule fonction avec un argument `type` est plus simple par certains aspects, notamment car toute la documentation est regroupée au même endroit, qu'on a qu'un seul nom de fonction à retenir et qu'on peut se référer à la documentation de cette fonction pour retrouver un format donné...

**Comment by larmarange** [comment]
Histoire de faire l'avocat du diable :

-* la documentation est d'ores-et-déjà réunie sur une seule page et il n'y a rien de plus facile que de réunir la documentation de plusieurs fonctions sur une seule page de documentation ;
-* là en l'occurence il y a deux noms à connaître : `myformat` et `ggmyformat` et il faut bien se souvenir dans quel cas utiliser l'une ou l'autre (en soit je trouve ça bien plus compliqué et tortueux...).
-* dans ton exemple tu utilises un argument `type` là où toutes les autres fonctions utilisent un argument `digits`. Est-ce à dire que tu aurais en tête de fusionner à la fois la famille des fonctions `fr`, `en`, `int`, `pourcent`, `percent`, `comp.pourcent` et `comp.percent` ? est-ce à dire qu'il y aurait alors en termes d'arguments : `type`, `lang` et `digits` ? N'est-on pas en train de compliquer la situation à vouloir faire générique ?

;-)

**Comment by juba** [comment]
Je vais répondre à l'avocat du diable, désolé, avec un peu de retard :-) 

- effectivement, regrouper la documentation des différentes fonctions sur une seule page ne pose pas de problème, et ça revient au même que ce que je proposais, donc un point pour toi.
- sur le fait qu'il y a deux fonctions et que ça rajoute de la complexité, c'est pas faux. Ça ne me semble pas extrêmement difficile à mémoriser, mais je veux bien t'accorder 1/2 point (oui, je sais, je suis mauvais perdant)
- je ne pensais qu'à un seul paramètre, mais je n'avais pas vu dans le code source de tes fonctions qu'il y avait un argument `digits` en plus. Ok, encore un point pour toi :-) 

Bref, est-ce que comme compromis on ne pourrait pas partir sur une série de fonctions, mais avec un préfixe commun ? Quelque chose comme `format_fr0`, `format_pourcent1`, `format_who`... (ça peut être autre chose que `format_`) ?

Merci de prendre le temps de la réflexion en tous cas.

**Comment by larmarange** [comment]
Et merci à toi de participer à cette réflexion commune. C'est bien le but d'un travail collaboratif.

En effet, utiliser un préfixe commun est une manière de "regrouper" ces différentes fonctions. `format_` a le mérite d'être explicite, même si ça allonge le nom des fonctions. 

Ceci dit, avec l'autocomplétion dans RStudio, c'est plus vraiement un problème : mieux vaut un nom explicite qu'un nom long.

Pour la mise en pourcentage, ne serait-ce pas meilleur d'avoir des noms comme format_percent_en2, format_percent_fr1  (aujourd'hui la différence entre anglais et français est assurée en utilisant  percent et pourcent ;-) )

Cdlt

**Comment by juba** [comment]
Oui, je me suis fait la même réflexion à propose de l'autocomplétion. Ça peut même être un avantage, "je  sais que la fonction commence par `format_`, donc je le tape ça et je vois ce qu'il me propose".

Pour le nommage, je crois que je vais te laisser choisir tranquillement pour une fois ;-) J'avoue que les deux options me conviennent.

**Comment by larmarange** [comment]
Il y a un ensemble de formatter dans `scales` : https://github.com/hadley/scales/blob/master/R/formatter.r

Du coup je ferme ici.
