### ISSUE TITLE
irec et vecteurs numériques

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#64]
Je viens de faire un test rapide et la fonction `irec` n'acceptent que des variables textuelles et des facteurs. Or, lorsqu'on importe des données en conservant les codes numériques (ce qui est le cas par exemple avec des données labellisées), on peut aussi avoir besoin de procéder à ce type de recodage, puisque notre variable numérique correspond dans ce cas à des données catégorielles.

Pourrait-on envisager l'évolution suivante ?

1. On peut transmettre à `irec` soit une variable numérique, soit une variable textuelle, soit un facteur (NB : les vecteurs labellisés sont bien inclus puisqu'ils restent par nature des vecteurs numériques et textuels, ce qui peut être testé avec `is.numeric` et `is.character`)
2. On supprime la case à cocher "transformer en facteur" et on propose à la place des boutons radios offrant le choix entre trois types de variables de sortie : numérique, textuelle ou facteur.

**Comment by larmarange** [comment]
Proposition supplémentaire :

Si (i) la proposition précédente est acceptée et (ii) l'extension labelled est finalisée et disponible sur CRAN, on pourrait proposer en plus, si le format de sortie est numérique ou textuel, de définir (optionnellement) des étiquettes de valeur et, y compris pour les facteurs, de définir une étiquette de variable.

**Comment by juba** [comment]
`irec` should now accept numeric vectors as input, and allows to choose between chracter, factor and numeric as output type. Don't know if it will be enough to work with labelled data, though.

Thanks for the suggestion.
