### ISSUE TITLE
irec doesn't accept a data.frame named "a" as input

### ISSUE THREAD

**Issue by scoavoux** [juba/questionr#67]
irec gives an error if we pass it a data.frame named `a` as the first argument.

	library(questionr)
        # simulate data
	d <- data.frame(l=letters[1:4],x=rnorm(100))
	a <- subset(d,l != "d")

	irec(d,l)
	# works fine

	irec(a,l)
	# Error in irec(a, l) : ‘a must be a data frame.’
	irec("a",l)
	# Error in irec(a, l) : ‘a must be a data frame.’

	exists("a")
	# [1] TRUE

	class(a)
	# [1] "data.frame"

**Comment by juba** [comment]
The problem came from a name conflict between the `a` object and the `a()` function from the `htmltools` package. I think it is solved by explicitly specifying the environment for `get()` and `eval()` calls, but don't hesitate to reopen this issue if the problem persists.

Thanks for reporting.
