### ISSUE TITLE
Adding data extracts

### ISSUE THREAD

**Issue by briatte** [juba/questionr#7]
I was thinking of adding various data extracts to the package. I have coded [a few download-and-prepare procedures](https://gist.github.com/briatte/6114696), based on publicly available data (others, like Anthony Damico, are doing at a higher level, with complex survey objects and so on).

Adding an ANES extract should be doable, since Martin Elff did it in `memisc` (see the package vignette, which uses the ANES 1948). The question is: adding a cross-sectional component or a longitudinal one. The latter might require adding panel functions to the package for consistency.

**Comment by juba** [comment]
CLosing this one as it is more than 2 years old. Don't hesitate to reopen if needed.
