### ISSUE TITLE
Non existent labelled::missing_val function

### ISSUE THREAD

**Issue by juba** [juba/questionr#79]
@larmarange : there's an error when checking the package, which comes from the use of `labelled::missing_val` in  the `.get_missing_val` function in `labelled.R`. It seems that this function no longer exists in `labelled`.

```
checking examples ... ERROR
Running examples in ‘questionr-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: describe
> ### Title: Describe the variables of a data.frame
> ### Aliases: describe describe.character describe.data.frame
> ###   describe.default describe.factor describe.labelled describe.numeric
> ###   print.description
> 
> ### ** Examples
> 
> data(hdv2003)
> describe(hdv2003$sexe)
[2000 obs.] 
nominal factor: "Femme" "Femme" "Homme" "Homme" "Femme" ...
2 levels: Homme | Femme
NAs: 0 (0%)> describe(hdv2003$age)
[2000 obs.] 
integer: 28 23 59 34 71 ...
min: 18 - max: 97 - NAs: 0 (0%) - 78 unique values> data(fecondite)
> describe(femmes$milieu)
Error: 'missing_val' is not an exported object from 'namespace:labelled'
Execution halted
```

Could you please take a look ? 

Thanks !

**Comment by larmarange** [comment]
Bonjour,

toutes mes excuses. En effet, la gestion des valeurs manquantes a changé dans `haven` et dans la foulée dans `labelled`. Et j'ai oublié de répercuter dans `questionr`.

J'essaie de mettre tout ça au propre et de t'envoyer une pull request ce vendredi ou ce week end.

**Comment by juba** [comment]
Aucun souci ! C'est juste que j'aimerais (peut-être, si j'y arrive, c'est pas sûr) mettre une nouvelle version de questionr sur le CRAN, mais ce ne sera pas avant plusieurs semaines. Du coup y'a aucun caractère d'urgence, c'est vraiment quand tu as la possibilité de jeter un coup d'oeil.

Merci !

**Comment by larmarange** [comment]
Je viens de mettre à jour labelled en version 1.0.0 et de soumettre à CRAN. Je vais mettre à jour questionr dans la foulée (une fois labelled sur CRAN).

Pour simplifier le code, peut-on envisager de rajouter `labelled` à la liste des packages importés par `questionr`?  Du coup, ca simplifierai un peu les choses (éviterai d'avoir ces fonctions intermédiaires comme `.get_var_label ()` et d'avoir à gérer une double maintenance).

En fonction, je mettrai à jour les fonctions `describe()` et `lookfor()`

**Comment by juba** [comment]
Oui, pas de problème pour importer labelled. Je te laisse mettre les `@import` ou `@importFrom` qui vont bien dans les documentations des fonctions en question ?

Grand merci en tous cas...

**Comment by larmarange** [comment]
C'est noté.

Une semaine assez chargée mais au plus tard ce week-end ça devrait être bon

Le dim. 20 nov. 2016 à 14:34, Julien Barnier <notifications@github.com> a
écrit :

**Comment by larmarange** [comment]
Je viens de préparer une pull request

**Comment by juba** [comment]
Je viens de faire le merge.

Merci !
