### ISSUE TITLE
Flexible syntax

### ISSUE THREAD

**Issue by briatte** [juba/questionr#8]
When you know R, a variable is `data$var` or `data[, "var"]`. But if you are learning R, perhaps `data, "var"` is a convenient notation too. This becomes handy when you are handling more than one variable, because `data[, c("var1", "var2")]` is painful, whereas `data, "var1", "var2"` is less painful.

[This issue](https://github.com/juba/questionr/pull/4) contains a similar suggestion.

I suggest implementing that syntax wherever possible, i.e. when it costs nothing else than modifying the call statement of a function and adding one line to pass the (variable) names to the data frame. I have no evidence to prove this might come out well, so it needs thought.

**Comment by juba** [comment]
Ok, closing this one as it is more than 2 years old. Don't hesitate to reopen it if needed !
