### ISSUE TITLE
A common behavior for lookfor, describe and freq.na

### ISSUE THREAD

**Issue by larmarange** [juba/questionr#83]
We have 3 functions that could be apply to a data.frame with an optional argument for selecting some variables. But they have different behaviours:

* for `describe`, by default, all variables are selected, and it is possible to provide several queries as multiple arguments: `describe(femmes, "un", "po")` Variable labels are not taken into account
* for `lookfor`, we can provide only one argument, but a regular expression is accepted and variable labels are accepted, `lookfor(femmes, "un|po")`
* for `freq.na`, by default only a limited number of variables are displayed.

I'm proposing to harmonize this different functions:

1. like `describe`, possibility of serveral arguments as multiple queries;
2. like `lookfor`, variable labels taken into account.

To avoid duplicated code, I'm proposing to update first `lookfor` and then to call that function in the others.

What do you think?

**Comment by juba** [comment]
I don't really use these functions, but harmonizing them seems a good idea.

Just pinging @briatte just in case...
