### ISSUE TITLE
Proposing a different approach than the describe function to generate codebooks

### ISSUE THREAD

**Issue by fBedecarrats** [juba/questionr#85]
Hello,
For now, it seems that `<describe>` only works with data imported with the foreign package and doesn't gives a description of the variable modalities.
Something like that would work for haven-imported dataframes:

>codebook <- function(x){
      library(labelled)
      nom = names(x)
      variable = var_label(x)
      modalites = val_labels(x, prefixed = TRUE)
      modalites = lapply(modalites, FUN = labels)
      modalites = lapply(modalites, FUN = paste, collapse = "; ")
      cb = cbind(nom, variable, modalites)
      cb = as.data.frame(cb, row.names = FALSE)
  return(cb)
} 

It creates a table with 3 columns : variable name, label and value labels.
I would be easy to adapt : 
 - to foreign-imported datasets (replacing val_labels by levels)
 - to complete with a column for variable type
 - add a vaiable with summaries

This is somehow refering to [this issue on haven repo](https://github.com/tidyverse/haven/issues/183) or [this one on questionnr repo](https://github.com/juba/questionr/issues/84).
Best regards,
FB

**Comment by juba** [comment]
cc @briatte and @larmarange 

 Thanks for taking the time to report the issue.

**Comment by larmarange** [comment]
Hi, did you try the last dev version?

Currently, `describe` already displays variables modalities. For example:

```r
> describe(femmes$milieu)
[2000 obs.] Milieu de résidence
labelled double: 2 2 2 2 2 2 2 2 2 2 ...
min: 1 - max: 2 - NAs: 0 (0%) - 2 unique values
2 value labels: [1] urbain [2] rural
```

Value labels are correctly shown, event if it's not through a table.

**Comment by larmarange** [comment]
Of course, it could be improved following https://github.com/juba/questionr/issues/84

**Comment by larmarange** [comment]
`lookfor`  is currently returning a data frame with variable and label.

We could think about an option to return a more detailed data.frame with variable type and value labels for labelled variable and levels for factors.

**Comment by fBedecarrats** [comment]
Thank you. As you mention, the limitation of `<lookfor>` is that it returns only variable label, not value labels.
I added two lines to the `<codebook>` function for class and type:

```r
codebook = function(x, fctr = FALSE){
  # On charge le package qui facilite la consultation/gestion des labels des variables
  library(labelled)
  nom = names(x)
  variable = var_label(x)
  vtype = lapply(x, typeof)
  vclass = lapply(x, class)
  modalites = val_labels(x, prefixed = TRUE)
  modalites = lapply(modalites, FUN = labels)
  modalites = lapply(modalites, FUN = paste, collapse = "; ")
  cb = cbind(nom, variable, vtype, vclass, modalites)
  cb = as.data.frame(cb, row.names = FALSE)
  return(cb)
}
```
To test it, you can do this:

```r
data("fertility", package="questionr")
codebook(children)
```
It returns:

   |         nom      |           variable           |         modalites
--|--------------|-------------------------|------------------
1  |    id_child       |          Child Id     |                        
2   |   id_woman   |             Mother Id    |                         
3 | date_of_birth   |         Date of birth    |                         
4   |        sex          |            Sex   |      [1] male; [2] female
5  |       alive     |        Still alive? | [0] no, dead; [1] yes, alive
6  age_at_death Age at death (in months)

**Comment by larmarange** [comment]
`lookfor` has been updated. You can now get value labels, factor levels and many other information with `details = TRUE`

For exemple `lookfor(women, details = T)`  will produce

|variable          |label                              |class                   |type   |levels |value_labels                                                                                                          | unique_values| n_na|na_values |na_range |
|:-----------------|:----------------------------------|:-----------------------|:------|:------|:---------------------------------------------------------------------------------------------------------------------|-------------:|----:|:---------|:--------|
|id_woman          |Woman Id                           |numeric                 |double |       |                                                                                                                      |          2000|    0|          |         |
|id_household      |Household Id                       |numeric                 |double |       |                                                                                                                      |          1814|    0|          |         |
|weight            |Sample weight                      |numeric                 |double |       |                                                                                                                      |           351|    0|          |         |
|interview_date    |Interview date                     |Date                    |double |       |                                                                                                                      |           165|    0|          |         |
|date_of_birth     |Date of birth                      |Date                    |double |       |                                                                                                                      |          1740|    0|          |         |
|age               |Age at last anniversary (in years) |numeric                 |double |       |                                                                                                                      |            36|    0|          |         |
|residency         |Urban / rural residency            |labelled                |double |       |[1] urban &#124; [2] rural                                                                                            |             2|    0|          |         |
|region            |Region                             |labelled                |double |       |[1] North &#124; [2] East &#124; [3] South &#124; [4] West                                                            |             4|    0|          |         |
|instruction       |Level of instruction               |labelled                |double |       |[0] none &#124; [1] primary &#124; [2] secondary &#124; [3] higher                                                    |             4|    0|          |         |
|employed          |Employed?                          |labelled_spss, labelled |double |       |[0] no &#124; [1] yes &#124; [9] missing                                                                              |             3|    7|9         |         |
|matri             |Matrimonial status                 |labelled                |double |       |[0] single &#124; [1] married &#124; [2] living together &#124; [3] windowed &#124; [4] divorced &#124; [5] separated |             6|    0|          |         |
|religion          |Religion                           |labelled                |double |       |[1] Muslim &#124; [2] Christian &#124; [3] Protestant &#124; [4] no religion &#124; [5] other                         |             6|    4|          |         |
|newspaper         |Read newspaper?                    |labelled                |double |       |[0] no &#124; [1] yes                                                                                                 |             2|    0|          |         |
|radio             |Listen to radio?                   |labelled                |double |       |[0] no &#124; [1] yes                                                                                                 |             2|    0|          |         |
|tv                |Watch TV?                          |labelled                |double |       |[0] no &#124; [1] yes                                                                                                 |             2|    0|          |         |
|ideal_nb_children |Ideal number of children           |labelled_spss, labelled |double |       |[96] don't know &#124; [99] missing                                                                                   |            18|  175|          |96-99    |
|test              |Ever tested for HIV?               |labelled_spss, labelled |double |       |[0] no &#124; [1] yes &#124; [9] missing                                                                              |             3|   29|9         |         |

**Comment by juba** [comment]
This seems really nice. Thank you !

**Comment by larmarange** [comment]
@juba : je pense que l'on peut fermer cette discussion

**Comment by juba** [comment]
Effectivement !
