### ISSUE TITLE
print method for odds.ratio

### ISSUE THREAD

**Issue by scoavoux** [juba/questionr#87]
`questionr:::odds.ratio.glm` inclut:

    stats::printCoefmat(r, signif.stars = TRUE, has.Pvalue = TRUE)

De ce fait, la fonction print nécessairement dans la console, même lorsque l'on ne le souhaite pas (par exemple, lorsque l'on veut l'utiliser comme une étape pour inclure les résultats dans stargazer).

Est-ce qu'il ne vaudrait pas mieux terminer par:
    
    class(r) <- "odds_ratio"
    return(r)

Et ensuite définir une méthode print.odds_ratio:

    print.odds_ratio <- function(x){
        stats::printCoefmat(x, signif.stars = TRUE, has.Pvalue = TRUE)
    }

Pour le contexte, voici ce que j'essaye de faire:

https://gist.github.com/scoavoux/ccb2f4333626949838a0ff807da238ff

**Comment by juba** [comment]
Ping @briatte, @larmarange (désolé, je ne sais plus qui est l'auteur des fonctions `odds.ratio`...)

**Comment by larmarange** [comment]
C'est moi qui avait développé `odds.ratio`.

Je regarde ça et j'essaie aussi de rattraper le retard sur d'autres questions.

**Comment by larmarange** [comment]
Pull request créée.

Pour @scoavoux, si besoin de manipuler plus finement les résultats d'un modèle, voir le package `broom`, plus générique et plus fexible

**Comment by juba** [comment]
Pull request mergée, un grand merci !

Je clos ici, n'hésitez pas à rouvrir si besoin.

**Comment by scoavoux** [comment]
Super, merci!
