### ISSUE TITLE
Improve overall package documentation

### ISSUE THREAD

**Issue by juba** [juba/questionr#9]
It would be great to provide some kind of documentation which would describe the different functions offered by questionr, and the way to use them.

I see two possible formats here :
- a knitr vignette in the package
- wiki pages in github 

Another question is to decide if this doc must be written in english or both in french and english.

**Comment by sfirke** [comment]
I am looking at survey-related R packages and was wondering how to use this package.  If it's still being actively maintained, +1 for a vignette - I came to GitHub hoping for one.

**Comment by juba** [comment]
Hi Sam,

The package is till actively maintained, even if the CRAN version is a bit outdated. I agree that we really miss a vignette or some sort of minimal documentation / functions list. Right now questionr appears more as a collection of functions than a coherent package.

I think the way to use it, even suboptimal, is to check the documentation for the functions list and see if there are things than can be of interest for you. The package is also mentioned in some introductory document for R, but mostly in french.

**Comment by juba** [comment]
Not ideal, but I just added `pkgdown` generated documentation pages at https://juba.github.io/questionr/

Closing this for now.
