### ISSUE TITLE
freq warning avec exclude=NA

### ISSUE THREAD

**Issue by scoavoux** [juba/questionr#92]
Dans la définition de `freq`, Comme `useNA="ifany"` est hardcoded dans `table()`, l'usage de `exclude=NA` produit un warning. Pourtant, il me paraît important d'avoir un moyen simple d'exclure les valeurs manquantes de freq.

À mon sens, il y a deux solutions:

1. rester avec l'option exclude et faire en sorte que useNA = "no" si NA %in% exclude
2. ajouter une option useNA à passer à table

La deuxième solution a pour avantage de permettre de spécifier `useNA="always"` mais pour inconvénient d'ajouter un argument à la fonction. La première est moins malléable, mais garantit la backward compatibility.

Je peux me charger d'écrire le code et de faire la pull request, mais je veux bien votre avis avant.

Pour reproduire le warning 

```
> library(questionr)
> 
> data("mtcars")
> mtcars$cyl[12] <- NA
> freq(mtcars$cyl, exclude=NA)
   n    %
4 11 35.5
6  7 22.6
8 13 41.9
Warning message:
In table(labelled::to_factor(x, levels), exclude = exclude, useNA = "ifany") :
  'exclude' containing NA and 'useNA' != "no"' are a bit contradicting
```

**Comment by juba** [comment]
Je pense qu'on va faire au plus simple, et juste supprimer le `useNA = "ifany"` du code de `freq`, qui ne sert pas à grand chose il me semble puisque par défaut on a un `exclude = NULL`.

Du coup en faisant comme ça le comportement par défaut ne change pas, et on peut utiliser `exclude = NA` sans warning.

N'hésite pas si tu vois un inconvénient à cette solution, et merci d'avoir pris le temps de signaler le problème.
