### ISSUE TITLE
Avec freq(), cum et sort sont incompatibles lorsque les NA ne sont pas la modalité la plus faible

### ISSUE THREAD

**Issue by scoavoux** [juba/questionr#93]
Dans `freq()`, lorsqu'il y a des valeurs manquantes, les options `sort` et `cum` produisent un résultat faux.

MRCE

```r
library(questionr)
data(iris)
set.seed(200)
iris$Species[sample(1:150, 40, replace = FALSE)] <- NA
freq(iris$Species, sort="dec", cum=TRUE)

```

output:

```
           n     % val%  %cum val%cum
virginica  40 26.7 36.4  26.7    36.4
NA         40 26.7  0.0  53.3    36.4
setosa     36 24.0 32.7  77.3    69.1
versicolor 34 22.7   NA 100.0      NA
```

expected output:

```
n     % val%  %cum val%cum
virginica  40 26.7 36.4  26.7    36.4
NA         40 26.7   NA  53.3      NA
setosa     36 24.0 32.7  77.3    69.1
versicolor 34 22.7 30.9 100.0     100
```

Il faudrait corriger le calcul de `%val` et de `val%cum` ; une autre possibilité (que je préfère à titre personnel) est d'ajouter une option pour forcer les `NA` sur la dernière ligne lorsque `sort` est utilisé. (très utile lorsque l'on en a beaucoup parce que cela facilite la lecture de tri à plat successifs: on va directement à la dernière ligne sur chaque tableau + facilite, dans le code, le calcul des % cumulés).

Proposition:
```r
freq(iris$Species, sort="dec", cum=TRUE, na.last=TRUE)
```
```
n     % val%  %cum val%cum
virginica  40 26.7 36.4  26.7    36.4
setosa     36 24.0 32.7  77.3    69.1
versicolor 34 22.7 30.9 100.0     100
NA         40 26.7   NA  53.3      NA
```

**Comment by juba** [comment]
Effectivement, merci pour le rapport de bug !

Ça devrait être corrigé, et j'ai suivi ta suggestion d'inclure une option `na.last`. Je l'ai positionnée à `TRUE` par défaut, car il me semble également plus logiques que les `NA` apparaissent en dernier.

Merci encore.

**Comment by scoavoux** [comment]
Super! Merci à toi de l'avoir implémenté. J'avais essayé de regarder comment faire ça et j'avais l'impression de m'embrouiller, alors que je vois qu'un simple rbind fonctionne.
