### ISSUE TITLE
Permettre un exclude avec les wtd.table

### ISSUE THREAD

**Issue by pgtpg** [juba/questionr#94]
Bonjour,

Tout d'abord, merci beaucoup pour votre package qui m'est très utile au quotidien :)

J'aurais juste une suggestion.

Il m'arrive souvent de faire des table d'où j'exclus certaines valeurs avec "exclude". Mais wtd.table de questionr n'a pas cette option, je dois donc rajouter une deuxième ligne de code qui exclut ou ne retient que certaines valeurs de cette wtd.table... Est-ce qu'il serait facile de rajouter cette option ?

Merci encore !

**Comment by juba** [comment]
Bonjour,

Merci pour la suggestion, a priori je viens d'ajouter une option `exclude` à `wtd.table`. Elle est disponible dans la version de développement de questionr, ou dans la version 0.6.2 qui sera prochainement disponible.

N'hésitez pas à me signaler tout problème ou dysfonctionnement.

**Comment by pgtpg** [comment]
Merci beaucoup ! Je testerai l'option et vous dirai si elle fonctionne.

**Comment by pgtpg** [comment]
Bonjour,
J'ai bien testé l'option, dans mon cas elle fonctionne parfaitement !
Merci encore !
